### PR TITLE
Add some icons

### PR DESCRIPTION
**Pull request by MrAngelos6**
I added some icons :

- Crédit Mutuel
- Fnac
- Reddcoin
- Winamax

This is my first PR, feel free to tell me if something is wrong.

### CODE REVIEW

**Comment by wokija** [comment]
Hi and welcome to the contributing team!

Everything seems in order although I think the icons would fit Delta better if you could round the corners a bit on Crédit Mutuel and Fnac. Don't hesitate if you need assistance.

Thank you!

**Comment by MrAngelos6** [comment]
I made the fixes thanks to @Otemachi 🤩 on the Delta's Discord

**Comment by wokija** [comment]
Thank you for taking the time to make the adjustments :)

Looking forward to see more of your creations

**Comment by MrAngelos6** [comment]
@wokija I'll fix it today !

**Pull request merged**
