### PR TITLE
DB Barrierefrei & DB Bahnhof live

### PR DESCRIPTION
**Pull request by KerstinMaur**
I tried my luck again and hope these two icons fit right into Delta. 🤤

### CODE REVIEW

**Comment by KerstinMaur** [comment]
@wokija, can you please check if those two icons are OK before Leif gets another shock? 😅

**Comment by wokija** [comment]
The document size is correct (192px x 192px) but the icon itself should be 153px x 153px instead of 172px x 172px.

I always use template.svg file included in Delta's github and select the form I want, remove stroke and add fill. That way you can never go wrong with icon size. I even created an empty svg file with both template and color palette that i use to start new projects instead of importing both every time.

**Comment by KerstinMaur** [comment]
Thanks for your guidance, @wokija. Please check again.

**Comment by wokija** [comment]
Both still aren't 153px x 153px. Are you using the template?

**Comment by KerstinMaur** [comment]
I tried it again. Please have a look, @wokija. 😓

**Comment by wokija** [comment]
Almost there! db_barrierefrei.svg is 154px x 154px and db_bahnhof.svg is 156px x 156px. I'm not sure of the method you're using though.

**Comment by KerstinMaur** [comment]
Oh no, what am I doing? At least it gets better from try to try. 🙈
I will send another version soon...

**Comment by KerstinMaur** [comment]
Is this icon fine?
avm_fritz_box_myfritz_smart_home

**Comment by wokija** [comment]
It appears to be fine

**Comment by KerstinMaur** [comment]
Thanks. Please check the re-fixed DB Bahnhof & DB Barrierefrei icons too, @wokija. 
I finally got the hang of it (hopefully). 😅

**Comment by wokija** [comment]
Look alright to me!

**Comment by KerstinMaur** [comment]
Finally! 🥳
You can merge now, @leifniem. 😅

**Pull request merged**
