### PR TITLE
Add some icons

### PR DESCRIPTION
**Pull request by blaiselcq**
Additions:

- Getaround
- La Bobine
- Citiz
- LibraryThing
- TicketToRide
- ScoreApp 7 Wonders
- Swile
- UGC
- Imgflip
- Luko
- Saisonkalender
- France identité
- Conjugaison
- EDF & Moi
- Santé wtw
- VerbEx

Link update:
- Carrefour
- Swissborg
- OpenFoodFacts

### CODE REVIEW

**Comment by blaiselcq** [comment]
Does updating icons.yml appends whatever is added to the existing component infos?

**Comment by flameshikari** [comment]
@blaiselcq if I understood your question correctly - yes, you can add missing ComponentInfos to existing icons like that (even multiple):

```yml
twitter:
  - com.twitter/com.twitter.MainActivity
  - com.twitter/com.twitter.StartActivity
```

**Comment by blaiselcq** [comment]
Okay thanks, I was wondering if it was invalidating the existing ComponentInfos.

Last time I contributed was with the old process, it is way nicer now

**Comment by GitGitro** [comment]
Hi!
I've applied some fixes for consistency, here's a few things to consider:
- `#56595B` Davy's grey as default Black

- `#FF837D` Coral pink as default Red

- If the original logo doesn't contain small details or doesn't make up most of the background layer (circle/square/etc.) as designed, keep the logo size between 73-80px

- don't use letters with accents for filenames

the icons overall are good just double check the contributing guidelines if not sure about something!

**Pull request merged**
