### PR TITLE
Fixed files + added icons

### PR DESCRIPTION
**Pull request by wokija**
- Added Kuroba icon
- Updated Badoo icon (will replace the original badoo.png, can always make either one of them alt)
- Fixed Passngr png file
- Fixed Aurora Store ComponentInfos
- Added additional ComponentInfos for Google Files (Using Google Files Go icon)

### CODE REVIEW

**Comment by leifniem** [comment]
Thanks for the continuous support!

**Comment by wokija** [comment]
No problem, glad you keep pushing updates now and then :+1:

**Comment by leifniem** [comment]
With 200+ request mails in 1 week i think i will need to 😂

**Comment by wokija** [comment]
Whoa that's a lot! Feel free to post them on your github if you'd like some help. Sometimes I become inactive because I don't see many used apps that need their icon done.

**Comment by leifniem** [comment]
I'll see if i can streamline the task because it was hell to gather the info already, but if i get around to it i'll make sure to inform you :)

**Pull request merged**
