### PR TITLE
Add Pods Companion

### PR DESCRIPTION
**Pull request by KerstinMaur**
This adds the missing icons from #147

### CODE REVIEW

**Comment by wokija** [comment]
You got to fix your icons size and shapes before I can merge your PR

**Comment by KerstinMaur** [comment]
Alright, I will try to send a fix this weekend.

Can you please check if the attached icon is fine?
flow

**Comment by wokija** [comment]
Sorry but no, corners radius is too high.

**Comment by KerstinMaur** [comment]
microsoft_flow

Is it looking fine now?

**Comment by wokija** [comment]
I don't think it's the correct radius again. Please follow the [tutorial svg file](https://github.com/Delta-Icons/android/blob/master/template_tutorial.svg) I added to the repo.

I didn't add my empty workspace but it contains all the shapes and sizing :)

**Comment by KerstinMaur** [comment]
Now?

microsoft_flow

**Comment by KerstinMaur** [comment]
Now?

microsoft_flow

**Comment by wokija** [comment]
Can you share the SVG file?

**Comment by KerstinMaur** [comment]
It is attached.
[microsoft_flow.svg.zip](https://github.com/Delta-Icons/android/files/6095480/microsoft_flow.svg.zip)

**Comment by wokija** [comment]
Still a bit off. Also it should be 153px x 153px instead of 192px x 192px

**Comment by KerstinMaur** [comment]
I updated the Pods Companion and Huawei FreeBuds icons. Are they fine now?
[iconsrework.zip](https://github.com/Delta-Icons/android/files/6097960/iconsrework.zip)

**Comment by wokija** [comment]
I'm afraid not. Pods companion has no rounded corners and Huawei Freebuds size is off.

Simply copy/paste the shapes from template_tutorial.svg under your current icons and resize the logos so they fit the shapes.

**Comment by KerstinMaur** [comment]
OK, I tried it.

Here is the Pods Companion:
[Pods (2).zip](https://github.com/Delta-Icons/android/files/6104039/Pods.2.zip)

**Comment by wokija** [comment]
Great! Just a bit off-center

**Comment by KerstinMaur** [comment]
Please have a look at the icons in the .zip.
[icons.zip](https://github.com/Delta-Icons/android/files/6177923/icons.zip)

**Comment by wokija** [comment]
Apart from sizing they look alright, except for the square shaped ones which don't have the correct corners radius. You can solve that by first resizing the whole icon to 153px x 153px and replacing the shape with the one from template_tutorial.svg (import svg file into your project file).

**Comment by KerstinMaur** [comment]
Is it fine now?
[Flow.zip](https://github.com/Delta-Icons/android/files/6178040/Flow.zip)

**Comment by wokija** [comment]
Yes, it's perfect!

**Comment by KerstinMaur** [comment]
> Yes, it's perfect!

Finally 😅

**Comment by KerstinMaur** [comment]
Are those fine too?
[threemore.zip](https://github.com/Delta-Icons/android/files/6178115/threemore.zip)

**Comment by KerstinMaur** [comment]
I will do the .xml stuff next week in another PR if that's OK.

**Comment by wokija** [comment]
> Are those fine too?
> [threemore.zip](https://github.com/Delta-Icons/android/files/6178115/threemore.zip)

Yes they're fine. However I'd switch the font of star citizen travel helper to Now if I were you. Other than that they're ready to be added :)

**Comment by KerstinMaur** [comment]
Alright, I switched the font. Please merge. I will update the .xml files in a few days.
Thanks again for your support! 👍

**Comment by wokija** [comment]
You're welcome! Thanks for taking the time to fix your icons :)

**Pull request merged**
