### PR TITLE
Add Saikou

### PR DESCRIPTION
**Pull request by chinh4thepro**

### CODE REVIEW

**Comment by moamedhagoo** [comment]
Add goldex - my orange - pixilart - anime slayer - asd player -  full data guard - ram clean up, listed them for the the most I want to the least

**Comment by moamedhagoo** [comment]
Also T3 arena and transparent widget been using this since about 6 months pls make them I will really appreciate it and I also donated from a while ago

**Comment by chinh4thepro** [comment]
I'm not even part of the team 💀

**Comment by wokija** [comment]
@moamedhagoo This is not the place to request icons. Besides, it's @chinh4thepro 's first commit ever in this repo.


Thank you for your first contribution! :)

Everything seems in order. I'll release next beta soon which will include this icon. You can save yourself some time and simply add lines at the end of appfilter.xml files when adding new icons. I sort both files from time to time for readability purpose.

**Pull request merged**
