### PR TITLE
Add 12 new icons and fix some others

### PR DESCRIPTION
**Pull request by kAoi97**

### CODE REVIEW

**Comment by leifniem** [comment]
Hey, could you elaborate on the changes you made to existing icons like the google ones and Notion?

They would be overwritten so i think we should be careful.

**Comment by leifniem** [comment]
@kAoi97 sorry forgot to tag you.

**Comment by kAoi97** [comment]
of course, I only update the old versions of notion and google photos for not responding to the iconological reality of the icon :)

**Comment by leifniem** [comment]
Manually merged locally. Will be available when i push it.

**Pull request closed without merging**
