### PR TITLE
Fix Pull Request #402 and add new icons

### PR DESCRIPTION
**Pull request by AbsurdUsername**
Also

Added:
- Alertify
- AnyList
- BuzzFeed
- Classic Power Menu
- ClevCalc
- Drops Japan
- Easy Voice Recorder
- Finsus
- FTX Pro
- Gamezone
- Graphene Apps
- HLTV
- KillApps
- Listy
- National Bank of Canada
- neutriNote
- PDF Reader
- Pomodoro Timer
- Privacy Dashboard
- Repainter
- Simple Dialer
- SimpliSafe
- Telegram Monet
- Track &amp; Graph
- Voyager
- Walnut

Updated:
- Swift Backup

Fixed:
- Tracker Control
- Gcam mod
- Pixel Launcher Mods

Updated Request List

### CODE REVIEW

**Comment by wokija** [comment]
Sorry but, sizing's still off on the square shaped icons from #402.

**Comment by AbsurdUsername** [comment]
> Sorry but, sizing's still off on the square shaped icons from #402.

Hold on what do you mean by sizing? they are 192x192 and centered, so I don't know what's off

**Comment by wokija** [comment]
I meant the corner radius is too high. You can use the square template with
50% opacity to see for yourself.

Le lun. 23 mai 2022, 13 h 46, AbsurdUsername ***@***.***> a
écrit :

**Comment by AbsurdUsername** [comment]
@wokija I see, kinda hard too spot, should be fixed for real [now](https://github.com/Delta-Icons/android/pull/420/commits/574d21abf3ec6a59a1ba9b1d5b44ee3be71b8c45), the others looks good to me

**Comment by AbsurdUsername** [comment]
@wokija ok I spotted them all, now it's ready to merge

**Pull request merged**
