### PR TITLE
Add Quake & United We Stream

### PR DESCRIPTION
**Pull request by NadineThouroghby**
[Quake](https://github.com/veetaw/quake) by @veetaw
[United We Stream](https://en.unitedwestream.berlin/)

### CODE REVIEW

**Comment by veetaw** [comment]
Niceee 🔥 !

btw icon is from @eskilop

**Comment by eskilop** [comment]
I'm flattered and super happy to see this, thanks 😍

**Comment by NadineThouroghby** [comment]
By the way, are you behind the [@qr_codebot](https://t.me/qr_codebot) Telegram bot, @veetaw?

**Comment by veetaw** [comment]
Yes I am, contact me on Telegram so we don't go off topic there. 

Sorry op!

**Pull request merged**
