### PR TITLE
Add new icons and more

### PR DESCRIPTION
**Pull request by AbsurdUsername**
Add requested icons:
- Alertable
- Amazon Shopper Panel
- AnyTracker
- Assistive Touch
-  Aves Gallery
- Bacon
- be
- BeWet
- Blued
- boAt Wave
- Book Reader
- ClassNotes
- Clozemaster
- Cricket Visual Voicemail
- Decathlon International
- DEGIRO
- DevCheck
- DioHub
- DKB
- DNSChanger
- EPIK
- EuroBank
- Expedia
- Experian Credit Report
- FastHabit
- FlorisBoard Beta
- Fluid Navigation Gestures
- GeeksforGeeks
- IHG
- InSquare Pic
- Kalender Indonesia
- LessPass
- Mi Cuenta DIGI
- My H-E-B
- MySudo
- N1 info
- NHS App
- Noice Podcast
- NOW
- Ocea for KWGT
- Office Reader
- Petco
- PlusMinus
- PostFinance App
- PowerAudio Pro
- Private Share
- Redditoria for Reddit
- retroPod
- Simple Music Player
- Spotistats for Spotify
- SwitchBot
- TextU
- TfL Go
- Tiny Weather
- TOTP Authenticator
- Trenord
- Twidere X
- Unilink Bus
- Up Si Vale
- Veo
- Very Mobile
- Veve
- VG
- VIMpay
- What's Up
- Zapya Go
- Zing MP3
- Zoho Desk

Fix component info
 -  Flickr
 

Update icon
- FlorisBoard

**Also I took the opportunity to remove all the dead/404 links from the requests file with a simple script, I hope that's okay**

### CODE REVIEW

**Comment by wokija** [comment]
Dead links are mostly apps from other sources like F-Droid or unknown sources. Even OEM apps not available through Google Play Store can be requested.

**Comment by AbsurdUsername** [comment]
> Dead links are mostly apps from other sources like F-Droid or unknown sources. Even OEM apps not available through Google Play Store can be requested.

I can revert the commit as you wish, you tell me

**Comment by wokija** [comment]
I think it'd be better to revert it even though I appreciate your effort to clean the requests :)

**Comment by AbsurdUsername** [comment]
Done!

**Pull request merged**
