### PR TITLE
Add Icons

### PR DESCRIPTION
**Pull request by KerstinMaur**

### CODE REVIEW

**Comment by leifniem** [comment]
Hey, i noticed you're trying to overwrite an existing icon with barcode scanner and your huawei icons both have a 1px stroke that i do think is a little conflicting with our overall design language. Is it okay if i ask you to fix these things? 😅

**Comment by KerstinMaur** [comment]
Oh, sorry. I did not want to overwrite the existing icon. My idea was to add it as a new one, so that we have `barcodescanner` and `barcode_scanner`.
What do you mean with the 1px stroke. I do not understand. 😅

**Comment by flameshikari** [comment]
> 
> 

> What do you mean with the 1px stroke. I do not understand. 😅
That stroke I guess.
image

**Comment by leifniem** [comment]
> > What do you mean with the 1px stroke. I do not understand. 😅
> 
> @KerstinMaur that stroke I guess.
> image

Exactly that 👍

**Comment by KerstinMaur** [comment]
Oh. 🙈

I will fix those two Huawei icons soon.

Do I have to change something regarding the QR reader or is that fine?

**Comment by KerstinMaur** [comment]
Please check my fixes. I hope they are fine now. 😅

I removed the shadow from the Searxer icon and overwrote the existing file. That should be fine, shouldn't it?

**Comment by wokija** [comment]
> I removed the shadow from the Searxer icon and overwrote the existing file. That should be fine, shouldn't it?
Current icon looks alright, why get rid of the shadow? Wasn't sure to overwrite so I skipped the file for now.

**Comment by flameshikari** [comment]
> I removed the shadow from the Searxer icon and overwrote the existing file. That should be fine, shouldn't it? Current icon looks alright, why get rid of the shadow? Wasn't sure to overwrite so I skipped the file for now.
> searxer

New variant is kinda strange. I think it would looks better if you only remove the shadow without resizing the magnifier. Something like that:

Searxer

**Comment by wokija** [comment]
My last comment was messed up; i quoted Kerstin but ended up responding inside the quote... The screenshot is a comparison from the pull request and it wasn't overwritten because the current one looks better but yeah it does look better without the shadow. Will add it.

**Comment by KerstinMaur** [comment]
Thanks for your help. You are awesome.

**Pull request merged**
