### PR TITLE
Add Fiverr & Tutanota + Update Scan

### PR DESCRIPTION
**Pull request by KerstinMaur**
Hi,
I added [Fiverr](https://play.google.com/store/apps/details?id=com.fiverr.fiverr) and [Tutanota](https://play.google.com/store/apps/details?id=de.tutao.tutanota). Additionally, I updated the [Scan](https://play.google.com/store/apps/details?id=me.scan.android.scan) icon and `AppFilter`. I am not sure about my changes in the `XML` files, please check them. 😅
Thanks @leifniem!

### CODE REVIEW

**Comment by leifniem** [comment]
Merged :) But be aware that i am not sure when i will build the next time, it might be a while :/

**Comment by KerstinMaur** [comment]
Can you please check Fiverr & Tutanota?
I cannot find them in the app you released today.

Additionally, please fix Speedtest:

org.zwanoo.android.speedtest/com.ookla.mobile4.screens.main.MainActivity
https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest

Thank you so much @leifniem!

**Comment by leifniem** [comment]
@KerstinMaur Fiverr and Tutanota were just pixel based icons saved as SVG's so i did not add them.

**Comment by KerstinMaur** [comment]
Can you please fix them @leifniem? 😅

**Pull request merged**
