### PR TITLE
Updated component info for Comico app

### PR DESCRIPTION
**Pull request by frugs**
https://play.google.com/store/apps/details?id=jp.comico&hl=en

### CODE REVIEW

**Comment by HiramLevitch** [comment]
Thanks @frugs 👍
By the way, did you register for the [Hacktoberfest](https://hacktoberfest.digitalocean.com/)?

**Comment by frugs** [comment]
I hadn't; thank you for bringing it to my attention! I'll do so right away :)

**Comment by HiramLevitch** [comment]
Can you do an icon for the [Transistor](https://github.com/y20k/transistor) [app](https://play.google.com/store/apps/details?id=org.y20k.transistor) maybe @frugs?
FYI @y20k

**Comment by frugs** [comment]
Ah, my icon-creation skills really aren't up to scratch - I think you would be better off trying yourself, or using the in-app icon-request feature.

**Comment by KerstinMaur** [comment]
Done @HiramLevitch 👌
https://github.com/Delta-Icons/android/pull/27

**Pull request merged**
