### PR TITLE
Add Banggood, Cryptomator & Gratus

### PR DESCRIPTION
**Pull request by KerstinMaur**
Banggood: [Homepage](https://www.banggood.com/) & [Google Play](https://play.google.com/store/apps/details?id=com.banggood.client)
Cryptomator: [Homepage](https://cryptomator.org/) & [Google Play](https://play.google.com/store/apps/details?id=org.cryptomator)
Gratus: [Homepage](http://gratus.xyz/) & [Google Play](https://play.google.com/store/apps/details?id=com.franco.gratus)

### CODE REVIEW

**Comment by KerstinMaur** [comment]
Deliveroo: [Homepage](https://deliveroo.de/de/) & [Google Play](https://play.google.com/store/apps/details?id=com.deliveroo.orderapp)
Dunkin Donuts: [Homepage](https://www.dunkin-donuts.de/) & [Google Play](https://play.google.com/store/apps/details?id=de.xroot.dunkindonuts)
Neato: [Homepage](https://www.neatorobotics.com/) & [Google Play](https://play.google.com/store/apps/details?id=com.neatorobotics.android)
Pi Manager: [Homepage](https://www.joncordeiro.com/) & [Google Play](https://play.google.com/store/apps/details?id=com.cordeiro.pimanager) (_also used for [Pi Control](https://play.google.com/store/apps/details?id=de.willytech.picontrol) & [RaspManager](https://play.google.com/store/apps/details?id=com.cea.raspmanager))_

**Comment by KerstinMaur** [comment]
Counter: [Homepage](https://roman.zone/) & [Google Play](https://play.google.com/store/apps/details?id=me.tsukanov.counter) & [source](https://github.com/gentlecat/counter) by @gentlecat
Hashr: [Google Play](https://play.google.com/store/apps/details?id=de.kodejak.hashr) & [source](https://github.com/kodejak/Hashr) by @kodejak
Kinguin: [Homepage](https://www.kinguin.net/7en/4kb) & [Google Play](https://play.google.com/store/apps/details?id=net.kinguin)
NINA: [Homepage](https://www.bbk.bund.de/) & [Google Play](https://play.google.com/store/apps/details?id=de.materna.bbk.mobile.app)

Fixed [Swipe Pro](https://play.google.com/store/apps/details?id=com.happening.studios.swipeforfacebookpro) & [Discord](https://play.google.com/store/apps/details?id=com.discord) (closes https://github.com/Delta-Icons/android/issues/18)

**Comment by KerstinMaur** [comment]
oBike: [Homepage](https://www.o.bike/) & [Google Play](https://play.google.com/store/apps/details?id=com.obike)
Plumble: [Source](https://github.com/acomminos/Plumble) & [Google Play](https://play.google.com/store/apps/details?id=com.morlunk.mumbleclient) by @acomminos

**Comment by KerstinMaur** [comment]
Futurama: [Homepage](https://www.cc.com/shows/futurama), [Petition](https://www.change.org/p/netflix-bring-back-futurama-13f89c1f-687b-4b59-bada-3e6f9dd5151d?recruiter=false&utm_source=share_petition&utm_medium=copylink&utm_campaign=share_petition) & [Google Play](https://play.google.com/store/apps/details?id=com.tinyco.futurama)
Hello World: [Homepage](https://helloworldapp.net/) & [Google Play](https://play.google.com/store/apps/details?id=helloworld.com.projecthelloworld)
JOBBÖRSE: [Homepage](https://jobboerse.arbeitsagentur.de/) & [Google Play](https://play.google.com/store/apps/details?id=de.arbeitsagentur.jobboerse)

**Comment by KerstinMaur** [comment]
Bierverkostung: [Source](https://bitbucket.org/jufickel/bierverkostung) & [F-Droid Store](https://f-droid.org/en/packages/de.retujo.bierverkostung/), by @jufickel
Offline Survival Manual: [Website](https://ligi.de/), [Google Play](https://play.google.com/store/apps/details?id=org.ligi.survivalmanual) & [Source](https://github.com/ligi/SurvivalManual ), by @ligi
Simple Dilbert: [Source](https://github.com/smarek/Simple-Dilbert) & [F-Droid Store](https://f-droid.org/packages/com.mareksebera.simpledilbert/), by @smarek

**Comment by ligi** [comment]
@KerstinMaur thanks

**Comment by KerstinMaur** [comment]
Flush: [Homepage](https://www.samruston.co.uk/) & [Google Play](https://play.google.com/store/apps/details?id=toilet.samruston.com.toilet)
Linienplan [Hannover](https://www.hannover.de/): [Mail](mailto:spdvmnt@gmail.com) & [Google Play](https://play.google.com/store/apps/details?id=spdvmnt.linienplanhannover)
MyHannover: [Homepage](https://www.my-hannover.de/) & [Google Play](https://play.google.com/store/apps/details?id=de.hafas.android.hannover)

**Comment by KerstinMaur** [comment]
Findster: [Homepage](https://getfindster.com/) & [Google Play](https://play.google.com/store/apps/details?id=com.getfindster.android.findsterduo)
Halma: [Source](https://github.com/dmitriy1morozov/Chinese_Checkers) by @dmitriy1morozov & [Google Play](https://play.google.com/store/apps/details?id=borsh.diploma_chinese_checkers)
Monument Valley 2: [Homepage](https://ustwogames.co.uk/) & [Google Play](https://play.google.com/store/apps/details?id=com.ustwo.monumentvalley2)
Remembear: [Homepage](https://www.remembear.com/) & [Google Play](https://play.google.com/store/apps/details?id=com.remembear.android)
Wahl-O-Mat: [Homepage](https://www.wahl-o-mat.de/bundestagswahl2017/) & [Google Play](https://play.google.com/store/apps/details?id=de.dreipc.wahlomat)

_Fix [Flixster](https://play.google.com/store/apps/details?id=com.wb.flixster) & [Conversations](https://play.google.com/store/apps/details?id=eu.siacs.conversations) by @siacs & @iNPUTmice ([Homepage](https://conversations.im/) & [Source](https://github.com/siacs/Conversations))_

**Comment by KerstinMaur** [comment]
EVENTIM: [Homepage](https://www.eventim.de/) & [Google Play](https://play.google.com/store/apps/details?id=de.eventim.mobile.app.Android) _(used for Brasil, Israel, Poland & UK too)_
Mixcloud: [Homepage](https://www.mixcloud.com/) & [Google Play](https://play.google.com/store/apps/details?id=com.mixcloud.player)
Travelist: [Homepage](https://www.facebook.com/travelistapp) & [Google Play](https://play.google.com/store/apps/details?id=com.zoomicelab.tlists)

**Comment by FionaHagen** [comment]
Can you please do those two icons @KerstinMaur?


Name: BQ Plus
Code: com.bq.wizardbq.insurance/com.bq.wizardbq.insurance.InsuranceInfoActivity
Link: https://play.google.com/store/apps/details?id=com.bq.wizardbq.insurance

com bq wizardbq insurance

Name: Dateien
Code: com.android.documentsui/com.android.documentsui.LauncherActivity
Link: https://play.google.com/store/apps/details?id=com.android.documentsui

com android documentsui

**Comment by KerstinMaur** [comment]
I will do them next month as an exception @FionaHagen. If you have one or two awesome open source that are not themed yet I might do them too. 😘
Please use the in-app request tool next year and do not forget to support @leifniem.

**Comment by FionaHagen** [comment]
I have one more from [bq](https://www.bq.com/). Changing the XML will be fine @KerstinMaur. There is already a similar icon in Delta.

Name: Soundrekorder
Code: com.bq.soundrecorder/com.bq.soundrecorder.activities.MainActivity
Link: https://play.google.com/store/apps/details?id=com.bq.soundrecorder

com bq soundrecorder

Regarding an unthemed open source icon I suggest [Joplin](https://github.com/laurent22/joplin) by @laurent22 and [Dir](https://github.com/veniosg/Dir) by @veniosg.

That's it. Thanks @KerstinMaur! 😘

**Comment by leifniem** [comment]
@KerstinMaur I was free enough to remove your banggood alt icon as it was rather tasteless and had nothing to do with the purpose of the app.

**Comment by KerstinMaur** [comment]
Sorry for being rather tasteless.

**Comment by leifniem** [comment]
As much as i appreciate your contributions i have noticed your icons being 192x192 in size, while that should be the size including padding. No big issue just if you keep up the contributions :)

Base Circles: 176*176 px
Base Rectangles: 152*152px

Thanks!

**Comment by leifniem** [comment]
Oh and please do not submit JPG Files embedded in SVG. The requirement is for neatless scaling of the icons which is simply impossible with Pixel-based images.

**Comment by KerstinMaur** [comment]
@leifniem I will try to follow that 😇

@FionaHagen The [bq](https://www.bq.com/) icons are merged with PR #32 (FYI @bq). I will do the [Joplin](https://github.com/laurent22/joplin) and [Dir](https://github.com/veniosg/Dir) icons later this month. Keep your eyes open.

**Comment by leifniem** [comment]
@KerstinMaur if you take a look at the `template.svg` file you'll see that there is a square in the middle padded by 20px on each side when scaled, as well a circle shape and 2 rectangles for more stretched rectangle shapes.

If you stay within these shapes and add appropriate space in between the shaped of an icon it will most likely look fitting in terms of sizing, compared to the rest of the icons.

The final 192 * 192 pixels file should include the space around the icon so the icons don't vary in size or look squeezed together.

At the final size rectangles will have rounded corners of 10px to match the rest of the set.

Since you're working with Illustrator that means you'll have to create a new document of 192 * 192px (don't worry, illustrator will keep it vector based, even with pixel sizes), place the template in it and you are good to go.

To get scalable SVG files you'll have to work with paths and shapes and not pixel images (you only use those for reference), like many of your contributions already were. Pixel images embedded in SVG files will only suffer severe quality losses on many screens.

Illustrator also has a good SVG Export under File -> Export if i'm not mistaken.

Hope that helps :)

**Comment by FionaHagen** [comment]
Thank you so much @KerstinMaur! 😘

**Pull request merged**
