### PR TITLE
Adds icon

### PR DESCRIPTION
**Pull request by Tripticon84**

### CODE REVIEW

**Comment by Tripticon84** [comment]
Would you like me to make a new pull request with the new auto method ? @flameshikari

**Comment by flameshikari** [comment]
@Tripticon84 sorry for taking so long with your PR, I was busy a little. Yeah, would be nice if you make a new PR with the new auto method, but there are issues with icons which need to be corrected. Tomorrow I'll describe what you need to fix here in comments.

**Comment by Tripticon84** [comment]
Ok, thank you

**Comment by flameshikari** [comment]
@Tripticon84, sorry again for the delay.

PurpleTV looks fine (just need to align the edges coordinates a bit, I'll take care of it), but LCL icons are a bit overloaded I think. They can be made much easier. Remove text below the logo (anyway it'll be hard to read), including the curvy shape. The location of the logo and the name of the application can be done as in the following examples. But in general, you can experiment with icons, send them to [#icon-review](https://discord.com/channels/743783969216135198/743784395856412782) in Discord and we will vote for the best variant. But if you wish you can take these icons and finish the rest based on them.

  

And don't forget to rename LCL icons like that (to make it easier to find them):

```
lcl_actu_patrimoine
lcl_assurances
lcl_bourse
lcl_essentiel_pro
lcl_ma_protection_maison
lcl_masante
lcl_mes_comptes
lcl_monem_mobile
lcl_paiement_mobile
lcl_pro_entreprises
```

**Pull request closed without merging**
