### PR TITLE
Add new icons

### PR DESCRIPTION
**Pull request by AbsurdUsername**
Add NeoApplications icons:

- NeoBackup (formerly OAndBackupX)
- NeoLauncher (formerly OmegaLauncher)
- NeoStore (formerly Droid-ify)
Leaving old icons as alt, and also leaving old build's component infos

New icons:

- APK Explorer & Editor
- Auditor
- BusyBox Installer
- Kernel Profiler
- Package Manager
- Power menu controls
- Secure Camera
- Secure PDF Viewer
- Simple Camera
- Simple Clock
- SmartPack
- sNotz
- The Translator

Add IconRequest to CONTRIBUTING.MD

### CODE REVIEW

**Comment by wokija** [comment]
Is there a specific reason for the removal of this line?:

`<AppIcon name="ComponentInfo{ca.chancehorizon.paseo/ca.chancehorizon.paseo.SplashActivity}" image="paseo"/>`

Just making sure before merging

**Comment by AbsurdUsername** [comment]
Just wrong syntax I didn't notice back then, it's **theme_resources.xml** so it should be


`<AppIcon name="ca.chancehorizon.paseo/ca.chancehorizon.paseo.MainActivity" image="paseo"/> without`
**ComponentInfo{}**

**Comment by wokija** [comment]
OH I didn't notice the wrong syntax, only compared its activity to another one from the same app. We can keep the line though, as well as it's equivalent in appfilter.xml files

**Comment by AbsurdUsername** [comment]
Thanks I was on mobile ❤️

**Pull request merged**
