### PR TITLE
16 icons (+2 resubmissions)

### PR DESCRIPTION
**Pull request by drygoatair**
So I already committed the Notes and Tasks icons in a previous PR but as they were still in the icons folder and the new_icons.yaml file was empty, I added them to this commit with better filenames.

### CODE REVIEW

**Comment by flameshikari** [comment]
Thanks for a lot for your input, but please, be more attentive when making icons.

- you're still trying to do transparencies where it can be easily avoided. for example, `passandroid`. this is how it can looks like (just quick examples, can be better aligned ofc):
passandroid icon_icon

  also these examples are more simplified (barcode/qr-code elements). you shouldn't make icons one-to-one, try it to do simpler but keep the idea
- `exist`, `hellrider3`: incorrect corners size
- `hellrider3`, `opp_app`: the background is transparent
- `hellrider3`: I understand that this icon repeats the original one, but I would suggest  to draw half of the logo more straight forward and reflect it
- not entirely critical, but try to solve the problem of your vectors icons, their size aren't 192x192px, they are bigger somehow. probably it's something with the artboard (this is how it's called in Illustrator, no clue about other editors)
- try to use the clipping mask. a very useful thing, you don't have to cut shapes to fit them within another
- also instead of making new icons for 'stock apps' (I mean, /e/OS apps), you could link them with existing icons like `aosp_mail` and `sms_alt_3`

I admit that some of what I said would be worth to note in the guidelines so that contributors would not have to fix issues later, so sorry for that. Don't hurry, make quality not quantity. I also have notes about your icons in previous PR, but I was busy and couldn't reply. I'll simplify them a little. You're doing great by the way!

**Comment by drygoatair** [comment]
Alright, I can do that! 

About the corner size though: the corners of passandroid icon are exactly the same as the template (I started using it as an underlay). Did you mean another icon or am I missing something?

**Comment by flameshikari** [comment]
> the corners of passandroid icon are exactly the same as the template 

Not exactly. They should be 10px.

image

**Comment by drygoatair** [comment]
Ah, should've zoomed in a bit more 🤦

I updated the icons: 

- Fixed corners, making them 10px 
- Got rid of all transparencies, 
- Updated my export settings so svg files are set to 192px x 192px 
- Simplified `passandroid`

I left the mail and sms icons as is, as they don't have a linked icon yet. This way they're set automatically after installing Delta.

**Comment by flameshikari** [comment]
I've fixed other unnoticed issues and reworked some icons in 3762525ba638948c3059f8e9589e4c7f791e467a

**Pull request merged**
