### PR TITLE
Added LCL icons

### PR DESCRIPTION
**Pull request by Tripticon84**
Added icons: 
- LCL Actu Patrimoine
- LCL Assurance
- LCL Bourse
- LCL Essentiel Pro
- LCL Ma Protection Maison
- LCL Ma Santé
- LCL Mes Comptes + 1 alt
- LCL Monem Mobile
- LCL Paiement Mobile
- LCL Pro & Entreprises

Removed request:
- LCL Paiement Mobile

### CODE REVIEW

**Comment by flameshikari** [comment]
There is no need to remove entries from `requests.txt` as this file will be processed automatically before the release.

**Comment by Tripticon84** [comment]
Oh ok my bad

**Comment by flameshikari** [comment]
It's okay, it's not forbidden. :D

**Comment by Tripticon84** [comment]
Thanks again for all the advice you gave me.

**Pull request merged**
