### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by miszek2000**
**Added icons** 
- Fit On
- Fitonomy
- Focusmaster
- Furgonetka
- G2A
- Gamepad Tester
- Geforce Now
- Genial Task
- Geocashing
- Glan
- Good Lood
- Grow
- Gwent
- Handy Cracow
- Hashme
- Hashtagify
- Hiking Map
- Horatio
- Hour Blocks
- Hue Essentials
- iCar
- Icon Pack Studio
- Ikea Home
- iMKA
- InPost
- Invision
- jakdojade
- Kahoot
- Karta Krakowska
- Keyforge
- KFC
- Kinolek
- Komoot
- Kupony
- Legimi
- Lime
- Liner
- Memorigi
- Meteo
- Metropolis
- mObywatel
- Moviebase
- Samsung Link Sharing
- Total Connect Comfort

**Added alternative icons** 
- Two new Lichess alternatives

### CODE REVIEW

**Comment by leifniem** [comment]
I will merge this when i get to work actively on Delta, it needs some manual merging, so no worries, not ignoring it :)

**Comment by wokija** [comment]
@miszek2000 I went through the xml files and didn't find ComponentInfos for the following drawable files:
kfc
karta_krakowska
moviebase

Also apparently we've both created Nvidia Geforce Now and Ikea Home icons. Both our version of Nvidia looked the same so I kept the one already in the repo. However I replaced my Ikea Home by yours since it looks prettier ;)

**Comment by miszek2000** [comment]
> @miszek2000 I went through the xml files and didn't find ComponentInfos for the following drawable files:
> kfc
> karta_krakowska
> moviebase
> 
> Also apparently we've both created Nvidia Geforce Now and Ikea Home icons. Both our version of Nvidia looked the same so I kept the one already in the repo. However I replaced my Ikea Home by yours since it looks prettier ;)

Ok, I must have missed this ComponentInfos. I will add them as soon as I get home. Thank you for cleaning up this PR :)

**Comment by wokija** [comment]
Np, looking forward to push a first update soon :+1:

Thanks for your contribution!

**Pull request merged**
