### PR TITLE
Added new icons

### PR DESCRIPTION
**Pull request by espositoandrea**
Hi!

I've added two new icons for the following apps:

- [Uniwhere](https://play.google.com/store/apps/details?id=lu.gian.uniwhere) (`lu.gian.uniwhere`)
- [MyUniba](https://play.google.com/store/apps/details?id=it.cineca.app.uniba) (`it.cineca.app.uniba`)

I've also fixed an error in the naming of a file (see #74).

### CODE REVIEW

**Comment by espositoandrea** [comment]
I've fixed some errors I made in my commit 68eb2b1a88ac4a67f52bb20d595ad47b477e14a5. I've also added a new icon:

- [Scanbot](https://play.google.com/store/apps/details?id=net.doo.snap) (`net.doo.snap`)

I've tried to stay as close as possible to the original.

**Comment by espositoandrea** [comment]
I've also created an open graph image for my fork. I thought that it could be useful :)


open graph image

**Comment by KerstinMaur** [comment]
Awesome, I love that. 😎
By the way, do you have time to design a [Santa Tracker](https://play.google.com/store/apps/details?id=com.google.android.apps.santatracker) icon? 😂

**Comment by espositoandrea** [comment]
@KerstinMaur I'm nothing near a designer :joy:, but I could try! Let's see what I can do!

**Comment by espositoandrea** [comment]
@KerstinMaur Let me know what you think of it! I'm pushing a commit right now: I just need to edit the various xml files :smiley: 

santa_tracker

**Comment by KerstinMaur** [comment]
Wonderful! Merry Christmas!! 🤶

**Comment by KerstinMaur** [comment]
If you find time, it would be great if you could do icons for [Statping](https://play.google.com/store/apps/details?id=com.statping) and [Namecheap VPN](https://play.google.com/store/apps/details?id=com.namecheap.vpn) too. Thanks! 🙏

**Comment by espositoandrea** [comment]
@KerstinMaur I'll work on them as soon as possible!

**Pull request merged**
