### PR TITLE
Added 7 Icon and 1 Alt Icon

### PR DESCRIPTION
**Pull request by Heruvetica**
Added:
- German Dicitionary (Netzverb)
- My We
- Prayer Times
- Proton Pass
- Quad9
- Quadline
- Status, Sticker Saver

Added Alt:
- Anilib

### CODE REVIEW

**Comment by Heruvetica** [comment]
Proton Pass was already added, I see.

**Comment by Heruvetica** [comment]
You can merge now if you wish!

**Comment by Heruvetica** [comment]
Sorry I haven't seen this message earlier. Gotta fix those right away.

**Comment by Heruvetica** [comment]
Done!

**Comment by flameshikari** [comment]
PNG icons are still missing spacing. If you're using Illustrator, be sure to check 'Use Artboards' when exporting.

image

I've resized those icons with some little icon fixes and merged it, but the next time make sure you're exporting icons correctly.

**Pull request merged**
