### PR TITLE
Add Folder Documents Icon

### PR DESCRIPTION
**Pull request by Mertyn**
I added this folder icon for grouping document and office apps nicely:
folder_documents

### CODE REVIEW

**Comment by KerstinMaur** [comment]
What do you think of those folders?

- **Music** (for apps like Spotify, Soundcloud, Poweramp, Phonograph, etc.)
- **Food** (for apps like Burger King, Lieferando, Too Good To Go, Nordsee, etc.)
- **Fitness** (for apps like Huawei Health, Runtastic, Mi Fit, Freeletics, etc.)
- **Transportation** (for apps like Öffi, DB Navigator, Citymapper, BVG, etc.)
- **Streaming** (for apps like Netflix, Disney+, Amazon Primve Video, YouTube, etc.)
- **Server** (for apps like Synolgoy, Termius, TotalCommander, Termux, etc.)

**Comment by Mertyn** [comment]
Those are some nice ideas @KerstinMaur and I'll take those into consideration for when I make some icons again. I am running out of colors from the palette though. It's already been a bit hard to find one for this icon already because all of the primary colors are already used up.

**Comment by KerstinMaur** [comment]
Maybe Leif can recommend some colors. I have problems with that too sometimes. 🥴
Thanks for your contributions! 😎

**Comment by leifniem** [comment]
@Mertyn Some folders already exist, make sure to take a look so you don't need to do unneccessary work. As for Colors: You can use a lot of secondary colors, like the darker shades of the main colors or shades of grey. Otherwise there are very few icons with gradients, but you could experiment with that too in case there are no other options.

**Comment by Mertyn** [comment]
Okay @leifniem thanks for the tips :)

**Pull request merged**
