### PR TITLE
Add GetYourGuide

### PR DESCRIPTION
**Pull request by MartinHennrich**

### CODE REVIEW

**Comment by leifniem** [comment]
Hi @MartinHennrich could you please add the ComponentInfo for this app, i noticed a lot of recent contributions missing them and fixing them by myself would eat up a lot of time. Thank you :)

**Comment by KerstinMaur** [comment]
Did you already do some CompentInfos stuff for #42 or can I add every icon in it?

**Comment by MartinHennrich** [comment]
Hey @leifniem, can you please check why that icon is not in your Google Play store release from today?

**Comment by leifniem** [comment]
@MartinHennrich if i'm not mistaken you were missing the ComponentInfo and the entry in the drawables.xml in your PR, which means the icon probably is included but not applying automatically because of that.

I failed to pay attention to that, but please also refer to the contribution guide in the README.md necessary files and changes are listed there.

**Comment by MartinHennrich** [comment]
Oh, I see. I will send a PR with them soon.

**Comment by MartinHennrich** [comment]
By the way, that app has two icons. How can I add that? 🤔
[https://f-droid.org/en/packages/com.forrestguice.suntimeswidget/](https://f-droid.org/en/packages/com.forrestguice.suntimeswidget/)

**Comment by leifniem** [comment]
You can send yourself a bug report through the Delta app, it has the ComponentInfos for the apps visible in the launcher.

**Pull request merged**
