### PR TITLE
Add new icons

### PR DESCRIPTION
**Pull request by riarsdev**
* ather
* cambly
* gpslogger
* hero_app
* shopsy
* tangedco
* tnepds

### CODE REVIEW

**Comment by flameshikari** [comment]
- `camlby`: use <code>#56595B</code> (Davy's grey)</span> as default Black color, <code>#FF837D</code> (Coral pink) as default Red and <code>#BA6561</code> (Fuzzy Wuzzy) as default Dark Red. shades of Red are specifically for shading purposes (according to [guidelines](https://github.com/Delta-Icons/android/blob/master/.github/CONTRIBUTING.md#rules-2))
- `hero_app`, `tangedco`, `tnepds`: not necessarily, just personal opinion — these logos would look nice without the text. just keep their size between 73-80px

**Comment by riarsdev** [comment]
Will update `cambly` and `hero_app`.

`tangedco` and `tnepds` are both government apps and have similar logos. Most of the government apps here have the same logo. So I used the name of the app (the name is more familiar here) and a relevant icon (which is not the official logo) from SVG Repo.

**Comment by flameshikari** [comment]
I noticed that your colors are shifted by one digit up per channel. For example, your orange color is <code>#F8C18C</code> when it should be <code>F7C08B</code>. Maybe you have an enabled layer with low opacity which is causing this.

Also notes about `gpslogger` (and in general):
- use <code>#56595B</code> (Davy's grey) as main black color in the icon. latest two black colors mostly used as a last resort when shading or something else special
- use transparencies as a last resort too. you can make shadows by using some of gray colors without using transparency

**Comment by riarsdev** [comment]
> I noticed that your colors are shifted by one digit up per channel. For example, your orange color is `#F8C18C` when it should be `#F7C08B`. Maybe you have an enabled layer with low opacity which is causing this (just stupid guesses).

Hadn't noticed that. I'll look into it.
> Also notes about `gpslogger` (and in general):
> * use `#56595B` (Davy's grey) as main black color in the icon. latest two black colors mostly used as a last resort when shading or something else special
> * use transparencies as a last resort too. you can make shadows by using some of gray colors without using transparency

oh okay. So I should use only those colors which are categorized under [`Basic`](https://github.com/Delta-Icons/android/blob/master/.github/CONTRIBUTING.md#palette) as main colors. Right? 

No worries. I'll review and update icons again. 😊

**Comment by flameshikari** [comment]
> oh okay. So I should use only those colors which are categorized under [Basic](https://github.com/Delta-Icons/android/blob/master/.github/CONTRIBUTING.md#palette) as main colors. Right?

Yes, always try to use colors only from Grays and Basic tables. In difficult cases, use others.

**Comment by riarsdev** [comment]
> I noticed that your colors are shifted by one digit up per channel. For example, your orange color is `#F8C18C` when it should be `#F7C08B`. Maybe you have an enabled layer with low opacity which is causing this (just stupid guesses).

The color for orange `#F7C08B` is not mentioned [here](https://github.com/Delta-Icons/android/blob/master/.github/CONTRIBUTING.md#colors). But `#F8C18C` _Pale Gold_ which I used is mentioned. 🤔

**Comment by flameshikari** [comment]
Funny, turns out it's my color palette is shifted somehow. Well, big sorry for that.

**Comment by riarsdev** [comment]
Fixed all icons. Hope its better now. ✌️

**Comment by flameshikari** [comment]
Awesome!

**Pull request merged**
