### PR TITLE
Add Icons

### PR DESCRIPTION
**Pull request by KerstinMaur**
- [x]  Doggy Time

- [x] [Tremotesf](https://github.com/equeim/tremotesf-android)

- [x] Motivation

- [ ] Huawei FreeBuds

- [ ] [Pods Companion](https://github.com/Domi04151309/PodsCompanion)

### CODE REVIEW

**Comment by wokija** [comment]
Again, Sizing was off with the circles and square. I fixed them but you'll need to do it yourself next time before I'm able to merge. Thank you!

**Comment by KerstinMaur** [comment]
Thanks again! 😍
Will I ever learn it? 😅

**Comment by wokija** [comment]
I'll add my empty workspace svg file to the project. Just start your new icons from that file. For shaped backgrounds, you'll only need to select the shape you want and modify color. Also planning to add a simple tutorial.

Sorry I merged your PR too, as you still had two icons to make in your list

**Comment by KerstinMaur** [comment]
Thank you so much!
Did you already add your empty workspace SVG?

**Pull request merged**
