### PR TITLE
Added 5 Icons + 1 Alt Icon

### PR DESCRIPTION
**Pull request by Heruvetica**
Icons Added:

- 2B
- Talabat
- Sarhne
- Wasla
- MAF Carrefour

Alt Icons Added:
- Google Authenticator (might become main in near future, old icon still there on android [new icon updated on iOS tho](https://apps.apple.com/us/app/google-authenticator/id388497605).

### CODE REVIEW

**Comment by vimalsonwani** [comment]
Canvas size must be 192x192px

**Comment by Heruvetica** [comment]
Reuploaded the files after fixing canvas size issue.
For the pngs I actually changed the dpi for exporting from the default 72 to 150 and that made my png exports larger as you noticed it. Good thing you noticed that!
For the svg I checked and they're still at the usual 192x192px so just reuploaded the svg files without any change.

**Comment by Heruvetica** [comment]
Also, I actually made the Google Authenticator Alt icon a bit smaller so that it would fit inside the template's circle icon size.

**Comment by flameshikari** [comment]
@Heruvetica

1. Filenames should match drawable names in YAML file (`Carrefour MAF.png`/`Carrefour MAF.svg` => `carrefour_maf.png`/`carrefour_maf.svg`); filenames and drawable names must be the same, keep them in lowercase and don't use spaces, only underscores
2. Alt icon names should be suffixed with a number, i.e. `google_authenticator_alt_1.svg`, even if it is the first alt icon
3. Make sure the logos are centered (I see that Wasla word isn't centered in SVG)
4. You can actually use that shape below for Wasla icon (set the word width to 110px), it will look better

image

Otherwise, everything seems to be cool!

**Pull request merged**
