### PR TITLE
Added icons and fixed a few things

### PR DESCRIPTION
**Pull request by wokija**
Added icons for the following apps:
Unit Converter Ultimate
Forest
Smart Life
Iseebiz
Material Files
Kiss Launcher
All-in-one Calculator (remake)
Air France
WienMobil
Carris
DVB Mobil
Lufthansa
MeinJena
Passngr
Tap Air Portugal
Probus London

Fixed:
Cleverbook icon not showing properly
Added Bouncer Alt, Caffeinate and Tiles icons (Forgot to include them in the last commit)
Renamed Pros and Cons png file
Wireguard svg (new version)
(Hopefully) Fixed Simple Gallery ComponentInfo - 2nd try
Forecastie ComponentInfo
Edited Tiles icon

### CODE REVIEW

**Comment by KerstinMaur** [comment]
I noticed something.

msp_rmm.png should be called solarwinds_take-control.png
and
msp-manager.svg is missing a .png version and needs to be renamed into solarwinds_msp-manager

Additionally, the activities changed:

Name: [MSP Manager](https://play.google.com/store/apps/details?id=com.solarwindsmsp.mspmanager)
Code: com.solarwindsmsp.mspmanager/md5f7ded89ee2a858f9d56d725e4a226048.SplashActivity

Name: [MSP RMM](https://play.google.com/store/apps/details?id=com.logicnow.remotemanagement)
Code: com.logicnow.remotemanagement/com.logicnow.remotemanagement.ui.screens.auth.FirstActivity
I will add a solarwinds_rmm.svg / solarwinds_rmm.png in my next PR somewhen next month. You might add the XML stuff already. 😅

Name: [Take Control Viewer](https://play.google.com/store/apps/details?id=sw.androidviewer)
Code: sw.androidviewer/sw.androidviewer.LandPage

Could you please fix that in your PR? Thank you so much! 🎅

**Comment by wokija** [comment]
I was doing the fixes when I noticed the ComponentInfo from MSP RMM seems to already be used by another icon

from theme_resources.xml:
`<AppIcon name="com.logicnow.remotemanagement/com.logicnow.remotemanagement.ui.screens.auth.AuthActivity" image="remote_monitoring" />`

Also, what is "Take Control Viewer" linked to?

**Comment by KerstinMaur** [comment]
Ah, I did not see that. Can you please rename remote_monitoring into solarwinds_rmm and apply the icon? It does not excactly fit the actual icon but it was used for the app earlier. So that should be fine. 🤔

Take Control Viewer is linked to the MSP RMM icon which is wrong.
msprmm
I suppose it needs a new entry in the XML files.

Another activity update:
Name: [LOVOO](https://play.google.com/store/apps/details?id=net.lovoo.android)
Code: net.lovoo.android/com.lovoo.ui.activities.phone.LovooStartActivity

**Comment by wokija** [comment]
Should be all fixed. LOVOO activity was already in the xml files btw.

I managed to create almost all icons of your transportation apps list too. Still need to do **Probus London** and **TAP Portugal**.

**Comment by KerstinMaur** [comment]
Wonderful, thank you so much! 👍

**Comment by KerstinMaur** [comment]
By the way, if you are in a Christmas mood you might do a [Santa Tracker](https://play.google.com/store/apps/details?id=com.google.android.apps.santatracker) icon. 🎅🏿
Otherwise I will continue next year.
Thank you so much and I wish you a very Merry Christmas and an amazing New Year! 🎉

**Comment by wokija** [comment]
It's kinda late for the Santa Tracker I think.

You're welcome! Merry Christmas to you too!

**Comment by KerstinMaur** [comment]
Can you please check if the ComponentInfo is fine for Easy Menu Planner? I think it changed.

Name: [Easy Menu Planner](https://play.google.com/store/apps/details?id=com.oscardelgado83.easymenuplanner)
Code: com.oscardelgado83.easymenuplanner/com.oscardelgado83.easymenuplanner.ui.SplashActivity

**Comment by KerstinMaur** [comment]
Those are the next four icons I will do. If you like, you can do the XML stuff already, @wokija. 😅

Name: [AI Life](https://play.google.com/store/apps/details?id=com.huaweioverseas.smarthome) by @Huawei
Code: com.huaweioverseas.smarthome/com.huawei.smarthome.login.LauncherActivity
File: huawei_ai_life.png
[website](https://consumer.huawei.com/en/audio/)

Name: [Aktion Mensch](https://play.google.com/store/apps/details?id=de.aktionmensch.AMMobileAppDistribution) by @aktionmensch
Code: de.aktionmensch.AMMobileAppDistribution/de.aktionmensch.AMMobileAppDistribution.activities.start.StartActivity
File: aktion-mensch.png
[website](https://www.aktion-mensch.de/)

Name: [Piwigo](https://play.google.com/store/apps/details?id=org.piwigo.android) by @Piwigo
Code: org.piwigo.android/org.piwigo.ui.launcher.LauncherActivity
File: piwigo.png
[source](https://github.com/Piwigo/Piwigo-Android)

Name: [Wakey](https://play.google.com/store/apps/details?id=com.sofaking.moonworshipper) by @sofakingforever
Code: com.sofaking.moonworshipper/com.sofaking.moonworshipper.ui.main.MainActivity
File: wakey.png
[website](https://wakey.app/)

**Comment by KerstinMaur** [comment]
I added four new icons to that PR, @wokija.

**Comment by wokija** [comment]
I'm currently sick. I'll look into it when I'm healed.

**Comment by KerstinMaur** [comment]
> 
> 
> I'm currently sick. I'll look into it when I'm healed.

Oh no, get well soon!
No need to hurry with it. Take your time and sleep a lot.

**Comment by wokija** [comment]
I'm off 1-2 weeks because of a spine-lumbar sprain. Can't force on anything but ain't in pain when I sit at the computer so I should get your ComponentInfo ready soon. 2020 hasn't been my lucky year so far lol.

**Comment by leifniem** [comment]
@wokija oh dang, please take care of yourself before going after any work. Get well soon and may your 2020 do so too :)

**Comment by wokija** [comment]
Thanks! Kinda need to feel helpful since I can't do much at the moment so it's the ideal thing to do at the moment.

**Comment by leifniem** [comment]
If it helps you sure :) If you mail me i can cut off a few cents from the Play Store donations for a get well soon pizza :P

**Comment by KerstinMaur** [comment]
All the best, if 2020 is starting that bad it can only end glorious. 
Thank you so much and take care!

**Comment by wokija** [comment]
@leifniem , thanks but it's not that bad haha, I got the OK to get back to work soon.
Thanks @KerstinMaur ! I've sent a new commit including your ComponentInfos.

**Pull request merged**
