### PR TITLE
Added 8 Icons

### PR DESCRIPTION
**Pull request by eeelbrens**
Added:
- AIO Store
- Skiff Mail
- Skiff Calendar
- Skiff Pages
- Skiff Drive
- Screen Off
- TimeSince
- TimeUntil

P.S. I realized I've passed my 100th icon in app mark since last update lol. My count is now 109 after this pull request gets merged (excluding Cryptee and Anilist in #672. I dunno how PWAs got implemented in Delta since then, that is if they got implemented officially in the first place),

### CODE REVIEW

**Comment by flameshikari** [comment]
I'm ok with replacing my Skiff Mail icon, as it looks same as other Skiff apps.

PWA support isn't implemented, and it's on CandyBar side (I don't know if it's possible to realize). I think we can use some placeholder as ComponentInfo for these PWA apps to replace it in the future.

**Comment by flameshikari** [comment]
@eeelbrens should there be a shadow in `timeuntil.png`?

**Comment by flameshikari** [comment]
Filling CompInfo for PWA apps is kinda useless, as CompInfo will be unique after creating the shortcut. So... probably we can fill it just with pwa.dummy/pwa.dummy to replace them in the future, and so that the script processes these icons.

**Comment by eeelbrens** [comment]
> Hi, congrats on passing the 100 icons! 🎉 
> 
> For skiff mail and others future icons don't replace them, but add them as alternative, especially if not made by you :) exceptions can be made of course
> For adding and alt refer [here](https://github.com/Delta-Icons/android/blob/master/.github/CONTRIBUTING.md#auto-method) or manually [here](https://github.com/Delta-Icons/android/blob/master/.github/CONTRIBUTING.md#manual-method). Rule of thumb if it already exists add as alt_(n+1)
> 
> As for the Anilist and Cryptee I don't know what happend I'll check on discord with the guys

So Skiff apps were already there before I made them? I checked the latest Delta beta beforehand and didn't find them. If the 4 apps are already there, I guess my icons or the old ones would do it doesn't really matter which ones.

**Comment by eeelbrens** [comment]
> @eeelbrens should there be a shadow in `timeuntil.png` or is this a mistake?

Yup. That's a shadow I put there.

**Comment by eeelbrens** [comment]
@GitGitro and also, next time I'd be checking icons directly from appfilter files 😂

**Comment by flameshikari** [comment]
> So Skiff apps were already there before I made them? I checked the latest Delta beta beforehand and didn't find them. If the 4 apps are already there, I guess my icons or the old ones would do it doesn't really matter which ones.

Skiff Mail was added in `new_icons.yml` after latest beta release and made by me. But anyway, you made 4 Skiff icons in one style, so whatever, I don't mind that you just replaced it with yours.

**Pull request merged**
