### PR TITLE
Added missing icons

### PR DESCRIPTION
**Pull request by joelchrono12**
image

### CODE REVIEW

**Comment by wokija** [comment]
Thank you for your contributions!

A few notes for future PR:
- Colors were a bit off (I fixed them)
  - We usually use `Davy's grey` as default black
  - As for colors, we try to stay in the palette's basic colors as much as possible. Red shades are there for shading only (Except for `Melon` which is used as default pink and `Light coral` as dark pink. Trying to keep the pastel theme going :)
- Background shapes of fildo and hoot mobile were 50% or so opacity which messed up the png icon files so be careful
- Spaces were used in XML files instead of tabulation.

**Comment by joelchrono12** [comment]
Thank you, yeah I knew I would have stuff like that, for some reason every color had some transparency by default after importing the template, I tried to fix the ones I noticed but I missed some.

Thanks for letting me know about the color usage, I should have read the guidelines with more care.

I actually imported the .gpl palette, so idk why would colors be wrong, is it possible that the palette itself is wrong?

**Comment by creepertron95** [comment]
I had created the .gpl palette using colors from the original .svg palette. I can check though to see if the colors are off.

**Comment by wokija** [comment]
Default palette includes transparencies so perhaps @joelchrono12 used those instead.

**Pull request merged**
