### PR TITLE
Added icons for Artstation, Castbox, Minisweeper, mobile.de and Screen Dimmer

### PR DESCRIPTION
**Pull request by Mertyn**
I have added icons for the aforementioned apps.
They look like this:
delta

I hope they are all to spec and that i did everything right in the ComponentInfo

### CODE REVIEW

**Comment by leifniem** [comment]
By the first look it looks all perfectly fine :) thank you very much!

**Comment by Mertyn** [comment]
Okay great @leifniem, I really like being able to contribute to an app that i actually use, even if it's just small :)

I just would really like a script where you can put in the drawable and package names that would then automatically add all of the different variants of it to the .xml files. I know you have that one python script in the root of the repo, but I didn't quite understand what it actually does in the end so I just didnt use it.
Could make one myself if I have the patience sometime though

**Comment by leifniem** [comment]
Sorry for getting back to you just now. I scripted a few tasks of creating the icon pack, so i should be able to script what you described some time. But if you'd like you can dig through the python scripts in the root of the repo and mash them together into a single script with your ideas :)

**Comment by Mertyn** [comment]
No biggie :)
Gonna look into making a script when I have some time and motivation

**Pull request merged**
