### PR TITLE
Add SVG icon for the app Whoosh

### PR DESCRIPTION
**Pull request by TraumaD**
Link to App:
https://play.google.com/store/apps/details?id=com.parkeon.whoosh

Original Icon:
whoosh-original

Purposed Icon:
whoosh

### CODE REVIEW

**Comment by leifniem** [comment]
Merged into my sketch file so it will be in the next update :)

**Comment by leifniem** [comment]
I can't find an appfitler for this app, can you provide one (most likely via application reader)

**Comment by TraumaD** [comment]
I've only really dealt with Linux icons so I don't really have any experience with android icon packs, but I did some googling. Is this what you need?

img_20170531_124220

**Comment by leifniem** [comment]
Last thing is exactly what I need :) where did you find it ?

Am 01.06.2017 15:41 schrieb "Micah Ilbery" <notifications@github.com>:

**Comment by TraumaD** [comment]
I installed an app called applicationreader that I found on one of those apk sites (apkpure.com I think) because it was no longer on the play store. It is what gave me the information in the screenshot above.

**Comment by leifniem** [comment]
Alright, just as I would do it. Will be in the update then, whenever I have
time to compile stuff.

Am 01.06.2017 15:51 schrieb "Micah Ilbery" <notifications@github.com>:

**Pull request closed without merging**
