### PR TITLE
Add Redfin, update AAA Auto Club, Roku

### PR DESCRIPTION
**Pull request by gideontong**
AAA Auto Club and Roku have other activities now. Also added Redfin.

### CODE REVIEW

**Comment by flameshikari** [comment]
Hello! Make sure that the square is 153x153px, PNG canvas is 192x192px (and the background is transparent).

**Comment by gideontong** [comment]
> Hello! Make sure that the square is 153x153px, PNG canvas is 192x192px (and the background is transparent).

Fixed the transparency on the canvas! The square is 153x153.

**Comment by flameshikari** [comment]
> The square is 153x153.

Not really!

image

**Comment by flameshikari** [comment]
I've fixed the icon size issues. Next time be more careful! Thanks for the 1st contribution by the way.

**Comment by gideontong** [comment]
> I've fixed the icon size issues. Next time be more careful! Thanks for the 1st contribution by the way.

Thank you! Will do

**Pull request merged**
