### PR TITLE
Add LinkedIn Learning

### PR DESCRIPTION
**Pull request by KerstinMaur**

### CODE REVIEW

**Comment by wokija** [comment]
Would it be possible for you to commit all your files at once instead of one by one? Thank you!

**Comment by KerstinMaur** [comment]
> Would it be possible for you to commit all your files at once instead of one by one? Thank you!

I am using the GitHub website and fear that it is not supported. 
Your idea is to keep the commit history smaller and clear, isn't it? Would it be an option if I simply send you the icons and ComponentInfos and you do the "Git stuff"?

**Comment by wokija** [comment]
> Your idea is to keep the commit history smaller and clear, isn't it?

Not really, but every admins get notifications each time a commit is made and grouping your changes will avoid spamming our inbox. Could you use Github client perhaps?

**Comment by KerstinMaur** [comment]
> > Your idea is to keep the commit history smaller and clear, isn't it?
> 
> Not really, but every admins get notifications each time a commit is made and grouping your changes will avoid spamming our inbox. Could you use Github client perhaps?

OK, I will try that.

**Pull request merged**
