### PR TITLE
Add Icons

### PR DESCRIPTION
**Pull request by KerstinMaur**
This is one commit only. 😃

### CODE REVIEW

**Comment by wokija** [comment]
You'll need to fix the icons sizing before I can merge. Thank you!

**Comment by KerstinMaur** [comment]
> You'll need to fix the icons sizing before I can merge. Thank you!

It should be fine now, @wokija. Otherwise I have to give up. 🙈

**Comment by wokija** [comment]
Yeah.. sizing's still off.

**Comment by KerstinMaur** [comment]
> Yeah.. sizing's still off.

F*c*, may you please fix them one last time please? 🙏

**Comment by KerstinMaur** [comment]
Thanks for your support, @AbsurdUsername! 🙏🏻

**Comment by wokija** [comment]
Closing this because fixed by AbsurdUsername in #420

**Pull request closed without merging**
