### PR TITLE
Gosund App Icon

### PR DESCRIPTION
**Pull request by maxpelic**
Added the app icon for the Gosund app

### CODE REVIEW

**Comment by leifniem** [comment]
Hey Max, thanks for your first contribution!

I think maybe the contents of the icon could be a bit smaller to fit more with the rest of the theme (you can look at PayPal and other rectangular icons for a rough idea on scale).

Just let us know if you are okay with changing it and if you want to give it a shot or want one of the admins to do it :)

**Comment by maxpelic** [comment]
Yeah I can do that, is there a way to update this pull request or do I need to make a new one?

**Comment by leifniem** [comment]
You should be able to just push to your fork and it will update afaik

Max Pelic ***@***.***> schrieb am Fr., 19. Nov. 2021, 23:42:

**Comment by maxpelic** [comment]
How does that look?

**Comment by leifniem** [comment]
Looks good as far as I can tell, merging it, thank you :)

**Pull request merged**
