### PR TITLE
Add Cephalon Navis

### PR DESCRIPTION
**Pull request by KerstinMaur**
[Cephalon Navis on Google Play](https://play.google.com/store/apps/details?id=com.cephalon.navis)
[Source](https://github.com/WFCD/navis) by @SlayerOrnstein and contributors

### CODE REVIEW

**Comment by leifniem** [comment]
Icon is not to spec, background does not adhere to the template.

**Comment by KerstinMaur** [comment]
Cephalon1

Is this one fine?

**Comment by leifniem** [comment]
@KerstinMaur sadly no. We use a certain shape for rectangular icons that you might remember from your previous PRs. You will see it in the template file :)

**Comment by KerstinMaur** [comment]
Oh, I slowly start to remember. 😅
The colors are fine though, aren't they?

**Comment by KerstinMaur** [comment]
I was creating another icon too. Is that one fine? 

hahabu1

**Comment by leifniem** [comment]
The colors do look about right, from what i can tell without testing, but your second icon also uses the wrong rectangle / sizing. If it helps check out the submitted-vectors folder and the template to get an idea. The rectangle itself needs to be sized 152x152px in a 192x192px canvas, so the exported icon will have 20px padding on each side. Also the contents of the rectangle should leave quite some space to the edges, but as i said for that it's best to check out submitted vectors and the template.

**Comment by wokija** [comment]
Closed due to inactivity

**Pull request closed without merging**
