### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by Danek309044**
Added 3 new icons + 1 alt. First time doing this so there is a chance that I broke something.

### CODE REVIEW

**Comment by GitGitro** [comment]
Yes, correct

**Comment by Danek309044** [comment]
Yikes, accidently changed thw height and width in the last icon

**Comment by flameshikari** [comment]
- Corners of the square template are not 10px.
- I see some sharpness between blue and gray layers in `alza` icon. You can fix this by extending gray layer under blue layer or play around with export settings.

image

**Comment by Danek309044** [comment]
Fixed all the icons, i hope that now they are all good.

**Comment by flameshikari** [comment]
Sorry, I forgot to mention: make `alza` logo 176px by height (keeping proportions), it will perfectly fit across all templates. And we're good!

**Comment by Danek309044** [comment]
Made it bigger!

**Comment by Danek309044** [comment]
Added one more icon that was on the request list.

**Comment by GitGitro** [comment]
you made probably by mistake the artboard huge😬 the last svg is correct but is tiny in the upper left corner, can you fix it?
is really simple just resize the document, thank you

**Comment by Danek309044** [comment]
Hi, yeah i will fix it as soon i will get home.

**Comment by Danek309044** [comment]
Fixed it. Well it was a very interesting mistake.

**Pull request merged**
