### PR TITLE
Update Rocket.Chat ComponentInfo

### PR DESCRIPTION
**Pull request by KerstinMaur**
Fix ComponentInfos
Add Some Icons

### CODE REVIEW

**Comment by KerstinMaur** [comment]
Please merge, @leifniem 😘

**Comment by KerstinMaur** [comment]
There is already a [Mirror](https://play.google.com/store/apps/details?id=com.koushikdutta.mirror) icon for a screen recording app. What do you think of renaming that icon so that "mirror" is available for mirrors

**Comment by leifniem** [comment]
@KerstinMaur feel free to rename the existing mirror icon to something like cwm_mirror and matching the changes throughout all files :)

**Comment by KerstinMaur** [comment]
Can you please take over, @wokija? I am using GitHub in the browser and the shown files are limited so that I cannot see that particular icon. Thanks!

**Comment by wokija** [comment]
No problem!

**Comment by KerstinMaur** [comment]
@wokija, do you have time to design an icon for Files?

Name: Material Files
Code: me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity
Link: https://play.google.com/store/apps/details?id=me.zhanghai.android.files

By the way, next month I plan to add some transportation apps. Are you interested in helping me?

**Comment by wokija** [comment]
Yeah sure. You can put the apps list and I'll edit the XML files

**Comment by KerstinMaur** [comment]
I was thinking about design support for that one too. Are you OK with that? 😅

**Comment by wokija** [comment]
I can give it a try

**Comment by KerstinMaur** [comment]
Very nice. 😎

You could design those please:

Name: {Air France[(https://play.google.com/store/apps/details?id=com.airfrance.android.dinamoprd)
Code: com.airfrance.android.dinamoprd/com.airfrance.android.totoro.ui.activity.main.MainActivity

Name: [WienMobil](https://play.google.com/store/apps/details?id=at.wienerlinien.wienmobillab)
Code: at.wienerlinien.wienmobillab/at.upstream.citymobil.feature.SplashActivity

Name: [Carris](https://play.google.com/store/apps/details?id=pt.carris.tecmic)
Code: pt.carris.tecmic/md544bae1e541e95037873c54c401f5c006.SplashActivity
[website](http://www.carris.pt/)

Name: [DVB mobil](https://play.google.com/store/apps/details?id=de.dvb.dvbmobil)
Code: de.dvb.dvbmobil/de.dvb.dvbmobil.MainActivity

Name: [Lufthansa](https://play.google.com/store/apps/details?id=com.lufthansa.android.lufthansa)
Code: com.lufthansa.android.lufthansa/com.lufthansa.android.lufthansa.ui.activity.HomeActivity

Name: [Material Files](https://play.google.com/store/apps/details?id=me.zhanghai.android.files) by @zhanghai
Code: me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity
[source](https://github.com/zhanghai/MaterialFiles)

Name: [MeinJena](https://play.google.com/store/apps/details?id=de.meinjena.app)
Code: de.meinjena.app/de.stadtwerkejenagruppe.meinjena.ui.activity.SplashScreenActivity

Name: [Passngr](https://play.google.com/store/apps/details?id=de.infogatesystem.passngr)
Code: de.infogatesystem.passngr/de.infogatesystem.passngr.presentation.start.StartActivity

Name: [Probus London](https://play.google.com/store/apps/details?id=org.probusdev.london.tfl.bustimes.journeyplanner)
Code: org.probusdev.london.tfl.bustimes.journeyplanner/org.probusdev.MainActivity
[website](http://www.probus-apps.com/london/tfl/)

Name: [TAP Portugal](https://play.google.com/store/apps/details?id=com.megasis.android)
Code: com.megasis.android/com.flytap.ui.LauncherActivity
[website](https://www.flytap.com/)

By the way, are you missing other icons too or are all your installed apps already themed?

**Comment by wokija** [comment]
When I install an app and notice it's missing from the icon pack, I add it to my to-do list. As of now, only my Pixel 3 "Files" is missing. Since it's a system app it doesn't seem to behave the same.

Looking at appfilter.xml, there are a few default icons:
`<item component=":BROWSER" drawable="browser" />
	<item component=":CALCULATOR" drawable="calculator" />
	<item component=":CALENDAR" drawable="calendar" />
	<item component=":CAMERA" drawable="camera" />
	<item component=":CLOCK" drawable="clock" />
	<item component=":CONTACTS" drawable="contacts" />
	<item component=":EMAIL" drawable="aosp_mail" />
	<item component=":GALLERY" drawable="gallery" />
	<item component=":LAUNCHER_ACTION_APP_DRAWER" drawable="app_drawer_three" />
	<item component=":LAUNCHER_ACTION_APP_DRAWER_NIGHT" drawable="app_drawer_eight" />
	<item component=":PHONE" drawable="phone" />
	<item component=":SMS" drawable="sms_alt_three" />`

@leifniem , would it make sense to add "FILES" in there? I ain't sure about the other xml files as I can't get find any ComponentInfo from my Files app.


Btw @KerstinMaur , I made Material Files already, not yet pushed a commit from my latest icons though!

**Comment by leifniem** [comment]
@wokija No, i don't think so. those are filter for Novas default dock apps, not overall generic ones.
What you could do is send a bug report to yourself and check the included activitylist.xml for your files app. Or feel free to send it to me if you aren't sure :)

**Comment by wokija** [comment]
@leifniem I see, I just remembered I installed an app called Activity Launcher from F-Droid which list all the activity with their componentinfo indicated although I can't copy them easily. I'll give it a try with my "Files" app.

**Comment by leifniem** [comment]
@wokija try the bug report first, i think that's definitely easier since you can choose where to send the zip file to. If that does not work Activity launcher allows you to edit and create shortcuts, which according to the play store screenshots include a Package and Class for a shortcut, which in the form of Package/Class result in the ComponentInfo i think

**Pull request merged**
