### PR TITLE
Add Icons

### PR DESCRIPTION
**Pull request by KerstinMaur**
@leifniem, can you please have a look at the [LibreLink](https://play.google.com/store/apps/details?id=com.librelink.app) icon? Is that OK?

### CODE REVIEW

**Comment by KerstinMaur** [comment]
Additionally to the rectangle [LibreLink](https://play.google.com/store/apps/details?id=com.librelink.app) and [LibreLinkUp](https://play.google.com/store/apps/details?id=org.nativescript.LibreLinkUp) icon, I added a round one with [Javvy](https://play.google.com/store/apps/details?id=io.hellocode.javvy). If you find any problems, please inform me @leifniem.

FYI @CMKlug

**Comment by KerstinMaur** [comment]
Liapp: [Homepage](https://www.marcelklug.de/), [Source](https://github.com/CMKlug/Liapp) & [Google Play](https://play.google.com/store/apps/details?id=de.cm.liapp)

Can I edit the xml myself @leifniem at this point? I see that you are updating [Candybar](https://github.com/danimahardhika/candybar-library) by @danimahardhika or doing other mysterious stuff (crazy Readme etc) at the moment.

_Here are the infos:_

Name: Liapp
Code: de.cm.liapp/de.cm.liapp.MainActivity
Link: https://play.google.com/store/apps/details?id=de.cm.liapp

Name: LibreLink
Code: com.librelink.app/com.librelink.app.ui.SplashActivity
Link: https://play.google.com/store/apps/details?id=com.librelink.app

Name: LibreLinkUp
Code: org.nativescript.LibreLinkUp/com.tns.NativeScriptActivity
Link: https://play.google.com/store/apps/details?id=org.nativescript.LibreLinkUp

**Comment by KerstinMaur** [comment]
Sorry, I forgot [Javvy](https://play.google.com/store/apps/details?id=io.hellocode.javvy). Here it is:

Name: Javvy
Code: io.hellocode.javvy/md5f48fe3905df5b9b0509d5bb1143ce871.MainActivity
Link: https://play.google.com/store/apps/details?id=io.hellocode.javvy

**Comment by KerstinMaur** [comment]
By the way, I wish all of you a Merry Christmas and a wonderful New Year!

christmasfailmcsanta

murry

**Comment by KerstinMaur** [comment]
Name: BiosBeepCodes
Code: es.smvarela.biosbeepcodes/es.smvarela.biosbeepcodes.BiosBeepCode by @smvarela
Link: https://play.google.com/store/apps/details?id=es.smvarela.biosbeepcodes

**Comment by KerstinMaur** [comment]
Hi @leifniem,
I will be away next month. It would be awesome if you could merge this PR and publish a new build [here on GitHub](https://github.com/Delta-Icons/android/releases) and on [Google Play](https://play.google.com/store/apps/details?id=website.leifs.delta) next month. 😉
I will continue with the contributions in February. 😁
I wish you a wonderful New Year! 🚀



giphy-downsized

**Comment by KerstinMaur** [comment]
Name: [Jager](https://play.google.com/store/apps/details?id=com.jaspervanriet.huntingthatproduct) by @JaspervanRiet
Code: com.jaspervanriet.huntingthatproduct/com.jaspervanriet.huntingthatproduct.Views.Activities.MainActivity
[source](https://github.com/JaspervanRiet/Jager) & [homepage](https://jaspervanriet.nl/)

Name: [Malwarebytes](https://play.google.com/store/apps/details?id=org.malwarebytes.antimalware)
Code: org.malwarebytes.antimalware/org.malwarebytes.antimalware.common.activity.SplashActivity
[homepage](https://malwarebytes.com/)

Name: [Star Wars](https://play.google.com/store/apps/details?id=com.disney.starwarshub_goo)
Code: com.disney.starwarshub_goo/com.disney.starwarshub_goo.activities.SplashActivity
[homepage](https://www.starwars.com/) & [YouTube channel](https://www.youtube.com/user/starwars)

**Comment by KerstinMaur** [comment]
Name: [Freshdesk](https://play.google.com/store/apps/details?id=com.freshdesk.helpdesk
) by @freshdesk
Code: com.freshdesk.helpdesk/com.freshdesk.helpdesk.fdlogic.ui.activity.LoginActivity
[homepage](https://freshdesk.com/) & [Twitter](https://twitter.com/freshdesk)


Name: [Pingdom](https://play.google.com/store/apps/details?id=com.pingdom.android.prime) by @Pingdom
Code: com.pingdom.android.prime/com.pingdom.android.pingdomapp.ui.home.HomeActivity
[homepage](https://www.pingdom.com/) & [Twitter](https://twitter.com/pingdom)

**Comment by KerstinMaur** [comment]
Name: [CyberGhost 6](https://play.google.com/store/apps/details?id=de.mobileconcepts.cyberghost) by @cyberghost
Code: de.mobileconcepts.cyberghost/de.mobileconcepts.cyberghost.view.launch.LaunchActivity
[homepage](https://www.cyberghostvpn.com/)

Name: [DO Swimmer](https://play.google.com/store/apps/details?id=com.yassirh.digitalocean) by @yassirh
Code: com.yassirh.digitalocean/com.yassirh.digitalocean.ui.MainActivity
[source](https://github.com/yassirh/digitalocean-swimmer) & [homepage](https://yassirh.com/)

Name: [MSP RMM](https://play.google.com/store/apps/details?id=com.logicnow.remotemanagement) by @solarwinds
Code: com.logicnow.remotemanagement/com.logicnow.remotemanagement.ui.screens.auth.AuthActivity
[homepage](https://www.solarwinds.com/)

Name: [Moodpath](https://play.google.com/store/apps/details?id=de.moodpath.android) by @moodpath
Code: de.moodpath.android/de.moodpath.android.feature.main.presentation.MainActivity
[homepage](https://www.moodpath.de/)

Name: [Pingdom](https://play.google.com/store/apps/details?id=com.pingdom.android.prime) by @pingdom
Code: com.pingdom.android.prime/com.pingdom.android.pingdomapp.ui.home.HomeActivity

Name: [PowerUp](https://play.google.com/store/apps/details?id=com.tailortoys.app.PowerUp)
Code: com.tailortoys.app.PowerUp/com.tailortoys.app.PowerUp.screens.ScreensActivity
[homepage](https://www.poweruptoys.com/?ref=github)

Name:  [PowerUpFPV](https://play.google.com/store/apps/details?id=com.codewithcontent.powerupfpv)
Code: com.codewithcontent.powerupfpv/com.codewithcontent.powerupfpv.intro.IntroActivity
[homepage](https://www.poweruptoys.com/?ref=github)

Name: [ZenMate](https://play.google.com/store/apps/details?id=com.zenmate.android) by @zenmate
Code: com.zenmate.android/com.zenmate.android.ui.screen.onboarding.OnboardingActivity
[homepage](https://zenmate.com/) & [Twitter](https://twitter.com/ZenMate)

**Comment by KerstinMaur** [comment]
Name: [11pets](https://play.google.com/store/apps/details?id=com.m11pets.elevenpets) by @11pets
Code: com.m11pets.elevenpets/com.m11pets.elevenpets.pDashboard.activityEntry
[homepage](https://www.11pets.com/) & [Twitter](https://twitter.com/11pets_com)

Name: [Petcube](https://play.google.com/store/apps/details?id=com.m11pets.elevenpets) by @petcube
Code: com.petcube.android/com.petcube.android.screens.splash.SplashActivity
[homepage](https://petcube.com/)

Name: [Puppr](https://play.google.com/store/apps/details?id=com.chinandcheeks.dogtrainer) by @ChinCheeks
Code: com.chinandcheeks.dogtrainer/com.chinandcheeks.puppr.MainActivity
[homepage](https://www.pupprschool.com/) & [Instagram](https://www.instagram.com/thesupercollies/)

**Comment by KerstinMaur** [comment]
Name: [Bumble](https://play.google.com/store/apps/details?id=com.bumble.app) by @bumble
Code: com.bumble.app/com.bumble.app.ui.launcher.BumbleLauncherActivity
[homepage](https://bumble.com/) :warning: **NSFW** :warning:

Name: [EDEKA](https://play.google.com/store/apps/details?id=com.valuephone.vpedeka) by @edeka
Code: com.valuephone.vpedeka/com.aperto.ext.edekaapp.EdekaMainActivity
Code: com.valiton.cnc/com.valiton.cnc.view.Splashscreen
Code: com.valiton.edeka24/valiton.com.edeka24.view.Splashscreen
[homepage](https://www.edeka.de/)

Name: [Tractive GPS](https://play.google.com/store/apps/details?id=com.tractive.android.gps) by @tractive
Code: com.tractive.android.gps/com.tractive.android.gps.ui.activities.LoginActivity
[homepage](https://tractive.com/), [blog](https://tractive.com/blog/) & [Instagram](https://www.instagram.com/tractive/)

Name: [VPN Unlimited](https://play.google.com/store/apps/details?id=com.simplexsolutionsinc.vpn_unlimited) by @vpnunlimited
Code: com.simplexsolutionsinc.vpn_unlimited/com.simplexsolutionsinc.vpn_unlimited.ui.activity.AuthActivity
[homepage](https://www.vpnunlimitedapp.com/affiliate?token=wmJCSzRFu2mjG15f2JYijDaG1B4cGX1pJsuV9OTOm61oWKC5KvOjv39ns7H2i4t7)

Name: [Zowi App](https://play.google.com/store/apps/details?id=com.bq.zowi) by @bq
Code: com.bq.zowi/com.bq.zowi.views.splash.SplashViewActivity
[homepage](https://zowi.bq.com/)

**Comment by KerstinMaur** [comment]
Name: [McDo France](https://play.google.com/store/apps/details?id=com.md.mcdonalds.gomcdo)
Code: com.md.mcdonalds.gomcdo/main.java.com.md.mcdonalds.gomcdo.activities.SplashscreenActivity

Name: [McDonald's](https://play.google.com/store/apps/details?id=de.mcdonalds.mcdonaldsinfoapp)
Code: de.mcdonalds.mcdonaldsinfoapp/com.mcdonalds.mcdcoreapp.common.activity.SplashActivity

Name: [McDonald's](https://play.google.com/store/apps/details?id=com.mcdonalds.mobileapp
)
Code: com.mcdonalds.mobileapp/mcdonalds.core.SplashActivity.Green

Name: [McDonald's](https://play.google.com/store/apps/details?id=com.mcd.lt.mcdonaldsbaltics)
Code: com.mcd.lt.mcdonaldsbaltics/com.mcd.lt.mcdonaldsbaltics.ui.activity.SplashActivity


giphy-downsized

**Comment by KerstinMaur** [comment]
Name: [Tagespresse](https://play.google.com/store/apps/details?id=com.dietagespresse.tagespresse) by @DieTagespresse
Code: com.dietagespresse.tagespresse/com.mobiloud.activity.SplashScreenActivity

**Comment by KerstinMaur** [comment]
Name: [Pr0n4Droid](https://mikandi.com/app/14791)
Code: com.pr0n4droid.android/com.pr0n4droid.android.activities.MainActivity
[homepage](https://pr0n4droid.com/) & [REDDIT](https://www.reddit.com/r/androidapps/comments/4osyxx/devnsfw_pr0n4droid_16_aka_a_fistful_of_dollars/) :warning: **NFSW** :warning:

**Comment by KerstinMaur** [comment]
Name: [Blynk](https://play.google.com/store/apps/details?id=cc.blynk) by @blynkkk
Code: cc.blynk/cc.blynk.activity.ProxyActivity

**Comment by leifniem** [comment]
Reviewed your icons. Way better this time, all vectors and most of the colors are close to the palette (i guess that's owed to the fact that humanity will never have perfect color management).

Two things that could be improved are the following:
- Create SVGs in 192x192 resolution, then stick to the template (Squares are 152*152px with 10px rounding, circles are 176px in diameter)
- Don't use autotrace on simple shapes. most results turned out good but Moodpath for example has some ugly double edges i needed to fix

**Comment by KerstinMaur** [comment]
Thanks @leifniem! 😘

**Pull request merged**
