### PR TITLE
Add Icons

### PR DESCRIPTION
**Pull request by KerstinMaur**
- [x] [AWS Console](https://play.google.com/store/apps/details?id=com.amazon.aws.console.mobile) by @aws

- [x] [FRITZ!Fon](https://play.google.com/store/apps/details?id=de.avm.android.fritzapp)

- [x] [Change Detection](https://play.google.com/store/apps/details?id=com.bernaferrari.changedetection) by @bernaferrari

- [x] [HAZ mobil](https://play.google.com/store/apps/details?id=com.newscope.news.haz) by @madsack

- [x] [Knockknock](https://play.google.com/store/apps/details?id=com.knocknock.app)

- [x] [Notes by Firefox](https://play.google.com/store/apps/details?id=org.mozilla.testpilot.notes) by @mozilla

- [x] [Scrittor](https://play.google.com/store/apps/details?id=com.shahid.nid) by @shahidshaikhs

- [x] [Simple Habit](https://play.google.com/store/apps/details?id=com.simplehabit.simplehabitapp)

### CODE REVIEW

**Comment by KerstinMaur** [comment]
Hi @leifniem, the PR is now ready to be merged. 😊

By the way, can you please check the [Bar Finder](https://play.google.com/store/apps/details?id=com.liveyourproject.barfinder) icon? I think that the last update downsized it. 🤔
photo_2020-05-25_23-56-01

**Comment by leifniem** [comment]
@KerstinMaur i regret to inform you that your commits show the usual issues:
- Icons lack padding according to the provided template
- Icons vary in size
- Rounded corners of 10px are not included in all icons.

So again please adhere to the following measurements:
- Files are to be exported at 192*192 pixels
- Square shaped icons are centered in those measurments and measure 152*152 pixels themselves with rounded corners of 10px
- Circular backgrounds are to be 176 pixels in diameter
- Icons without any background should match the optical sizing of the icon pack and are best sized with the help of the template

**Comment by KerstinMaur** [comment]
Hey Leif, sorry for the usual issues. 😓 
I hope I can fix them next week. 

By the way, do you plan to design an icon for the [German Corona-Warn-App](https://corona-warn-app.de) yourself?

**Comment by leifniem** [comment]
Yes, it's in the list for #96

**Comment by KerstinMaur** [comment]
Sorry, I won't be able to fix the icons this or next week. 😔
Can someone take over maybe?
@wokija or @miszek2000 probably?

**Comment by miszek2000** [comment]
@KerstinMaur I'm on vacation now. I can work on it when I'm back (10th of July) if it still will be available.

**Comment by wokija** [comment]
I fixed the icons. Not sure if I can just drop them here or if I should push them with my own commit though.

**Comment by leifniem** [comment]
> I fixed the icons. Not sure if I can just drop them here or if I should push them with my own commit though.

You could clone the fork and merge it into your version of the repo or you just open your own PR and i will close this one with a reference to it.

**Comment by wokija** [comment]
Can you still pull the XML files from this one or should I go ahead and copy them in my PR?

**Comment by leifniem** [comment]
> Can you still pull the XML files from this one or should I go ahead and copy them in my PR?

I can use them :)

**Comment by KerstinMaur** [comment]
Thanks for saving me again 🙏

**Comment by wokija** [comment]
> Thanks for saving me again

No problem! I'm in a productive state right now :)

**Pull request merged**
