### PR TITLE
Add Icons

### PR DESCRIPTION
**Pull request by KerstinMaur**

### CODE REVIEW

**Comment by leifniem** [comment]
Malmal Icon does not match requirements and Componentinfos are missing in files.

Will merge once that's fixed.

**Comment by KerstinMaur** [comment]
What is the issue with malmal?

**Comment by leifniem** [comment]
The rectangle is too big and too rounded. The usual square icon is 152 * 152 px centered in the 192 * 192px icon, with the corners rounded by 10 px.

Further issues i noticed with your last batch of icons:
- Colors varying from the provided palette
- Icons having bezels and shadows when there is no need for it (keeping it minimalistic is the essence of this pack)
- Sizes of icons varying heavily from the key shapes provided by the icon template
- Inconsistencies in size even between the same basic shapes (squares being too big, too small, not rounded etc.)
- Filenames containing characters besides underscores and lowercase alphabet (your file names including dashes cause errors and stop the build process)

**Comment by KerstinMaur** [comment]
Oh, sorry for the trouble. I will send a fixed icon soon. 😢

Do you know why the icons for [Bar Finder](https://play.google.com/store/apps/details?id=com.liveyourproject.barfinder), [BoxToGo](https://play.google.com/store/apps/details?id=de.almisoft.boxtogofull) and [Spritz Reader](https://play.google.com/store/apps/details?id=com.ausichenko.spritzbubble.pro) are not applied though I found them in the XML files? 🤔

**Comment by leifniem** [comment]
Spritz Reader is in the drawables folder, so if it is in the xml files it must be a mismatch between component infos. for boxtogo and bar finder i seem to have dismissed them when they lacked componentinfos to not increase the bundle size with unused icons. I'll look into it.

**Comment by leifniem** [comment]
BoxToGo was in my eyes not of acceptable quality, but i fixed it since the original icon really is a joke itself. BarFinder was missing i reexported it.

**Comment by KerstinMaur** [comment]
Thanks for your support. 🙏🏻
I (hopefully) fixed malmal. Can you please have a look and merge if everything is fine?

**Comment by KerstinMaur** [comment]
malmal

**Comment by KerstinMaur** [comment]
Please merge, @leifniem. 🙏

**Pull request merged**
