### PR TITLE
Add new icons

### PR DESCRIPTION
**Pull request by RENOMIZER**
Added icons for: 
- Ace Attorney Investigations
- Habit Builder
- Megafon Cleaner

Also tried fixing Image Toolbox icon which appears to be missing for some reason, but it went nowhere. Maybe someone else will get how to fix it.

### CODE REVIEW

**Comment by flameshikari** [comment]
@RENOMIZER, hi!

I've fixed Ace Attorney icons (in the circle variant there were no shades and there was red pixel stroke).

Also, outline the logo of Megafon Cleaner, please.

**Comment by flameshikari** [comment]
I have no idea where `Image Toolbox` might be. Maybe someone renamed it?

**Comment by RENOMIZER** [comment]
Image Toolbox uses `image_resizer_shrinker` icon, but when using the latest version it does not change. I thought it was because the ComponentInfo differed and indeed it did, but even after adding new ComponentInfo field it still didn't work. I thought maybe it was because of the launcher, so I tried another one. Nope, still doesn't change.

I've added slight shadow around the logo. Will this much be enough?

**Comment by flameshikari** [comment]
Try to build FOSS version and check if `Image Toolbox` has an icon.

Also, now there is no logo for Megafon Cleaner. I mean, you should convert the logo to a vector object. I think you're using a font with icons and I can't see that icon because I don't have that font installed. And other people won't see it.

image

**Comment by RENOMIZER** [comment]
Converted font to path, so now you should be able to see it.

And yes, the icon for Image Toolbox is now present.

**Pull request merged**
