### PR TITLE
Added Google Pay's new icon

### PR DESCRIPTION
**Pull request by VaibhavKothi**

### CODE REVIEW

**Comment by leifniem** [comment]
Apparently this change is only made to Get, not the international Google Pay. Do you think you can fix the PR to reflect that? If not feel free to ask for help :)

**Comment by VaibhavKothi** [comment]
Just added svg and png files, am not aware of the code part, if you can do the changes needed (or let me know how, as I will be contributing regularly from now), it would be great

**Comment by wokija** [comment]
If you take a look at the contributing section in README.md (or on the main page of this project) you'll have all the infos you need to add the apps ComponentInfos in all XML files specified.

They're two way to find the ComponentInfos:
Install [Icon Pusher](https://play.google.com/store/apps/details?id=dev.southpaw.iconpusher) which send the ComponentInfos of the apps you've selected on a database for easy copy/paste on your computer.

You can also go in Delta app settings and press Report Bugs, switch the email to yours and you'll find the apps ComponentInfos in activity_list.xml

It's simple copy/paste, no coding required ;)


Also, besides for drawable.xml files that needs to be ordered by letter, you can simply add the ComponentInfos lines at the end of the other files (after the last ComponentInfos of course). I actively wasted my time a lot at first by pasting the lines following alphabetical order and it's really not necessary to do so.

**Comment by wokija** [comment]
Added icon manually, closing PR

**Pull request closed without merging**
