### PR TITLE
Added three new icons.

### PR DESCRIPTION
**Pull request by free-sandwiches**

### CODE REVIEW

**Comment by GitGitro** [comment]
[we usually use more padding in the icons](https://github.com/Delta-Icons/android/blob/master/.github/CONTRIBUTING.md#rules-1)
could you resize a bit dmw and comics plus?

**Comment by free-sandwiches** [comment]
Sure, can do. How much padding is appropriate? The guidelines speak to the shape and color but not to padding, as far as I can tell.

**Comment by GitGitro** [comment]
it's above the shape, maybe I'll highlight it better later, anyway

> If the original logo doesn't contain small details or doesn't make up most of the background layer (circle/square/etc.) as designed, keep the logo size between 73-80px

sometime i stay even between 75-90px, to not make too much smaller

**Comment by free-sandwiches** [comment]
Ahh, my bad! Updated those icons as requested.

**Comment by GitGitro** [comment]
No worries! thanks!

**Pull request merged**
