### PR TITLE
Added multiple new icons and fixed some stuff

### PR DESCRIPTION
**Pull request by Mertyn**
### Icons added
- HSMWmobil
- Kfz-Kennzeichen
- OnePlus Camera
- OnePlus Gallery
- Tool Box
- YouTube Vanced Alt Two
- YouTube Vanced Alt Three

### Fixed icon
YouTube Vanced Alt was not symmetrical and did not fit into the template rectangles.

### Fixed XML Data
- Screen Dimmer ComponentInfo was wrong
- SIM Toolkit was missing ComponentInfo on OnePlus phone

### Notes
- Colors in OnePlus Gallery icon may be adjusted if needed, it was pretty hard to find colors that fit the palette or fit the vibe.
- Should OEM specific icons come before the generic ones or after (in xml files)? The order I gave them may be changed if needed.

### CODE REVIEW

**Comment by leifniem** [comment]
Yay I'm no longer the only German of the Delta crew :D

**Comment by leifniem** [comment]
OnePlus gallery looks fine by me, if those colors are from the palette I don't see a problem.

**Comment by leifniem** [comment]
Regarding the OEM appfilters: feel free to overwrite the generic ones. Your icons are more specific than the ones we use at the moment, therefore it makes sense to use them first. The people still have the option to use the generic ones as alts.

**Comment by Mertyn** [comment]
> OnePlus gallery looks fine by me, if those colors are from the palette I don't see a problem.

Well exactly that was the problem. There are no colors on the palette that are equivalent and so i tried making my own that are in the same spirit.
So you decide if it's still okay or if there are changes needed to be made :D

**Comment by leifniem** [comment]
I'll take another specific look at it once I'm at my desktop again :)

Mertyn ***@***.***> schrieb am So., 8. Aug. 2021, 12:58:

**Comment by leifniem** [comment]
@Mertyn i think this is within a reasonable range of desaturation, or would you disagree? The right version uses the palette we have.

If it's okay with you i'd overwrite the files with those changes.

Also if you're not already part of the Discord feel free to join us, we have an icon-review channel for things like this :)

grafik

**Comment by Mertyn** [comment]
> @Mertyn i think this is within a reasonable range of desaturation, or would you disagree? The right version uses the palette we have.
> 
> If it's okay with you i'd overwrite the files with those changes.
> 
> Also if you're not already part of the Discord feel free to join us, we have an icon-review channel for things like this :)
> 
> grafik
> 

Yeah feel free to overwrite it :)

Also will join the discord next time i make some icons :)

**Comment by wokija** [comment]
Thanks for fixing Youtube Vanced. The default Delta icons are outdated though if you ever want to work on new ones :)

**Pull request merged**
